---
- name: Download 7-Zip 
  hosts: localhost  
  become: yes
  vars_files:
    - vars.yml  

  tasks:
    - name: Ensure download directory exists
      file:
        path: "/tmp"
        state: directory
        mode: '0755'

    - name: Download 7-Zip 
      block:
        - name: Attempt to download 7-Zip
          get_url:
            url: "{{ seven_zip_url }}"
            dest: "{{ seven_zip_installer }}"
          register: result

        - name: Display success message
          debug:
            msg: "7-Zip  downloaded successfully to {{ seven_zip_installer }}"
          when: result is succeeded

      rescue:
        - name: Handle download failure
          debug:
            msg: "⚠️ Failed to download 7-Zip . Please check the URL or network connection."

      always:
        - name: Cleanup file on failure
          file:
            path: "{{ seven_zip_installer }}"
            state: absent
          when: result is failed
